# Generated by Django 5.2.7 on 2025-11-15 10:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_user_todo_created_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_todos', to=settings.AUTH_USER_MODEL),
        ),
    ]
